### ISSUE TITLE
Error: Found multiple Projects , data env0_project

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#184] opened 2021-12-15 03:48 UTC
When using the data env0_project resource by name only, will result in env0 complaining that there are duplicated IDs.

Using project IDs is particulary cumbersome, and that is why I want to use the data resource.  But the data resource should only return active projects, not archived/deleted projects.

```
 Error: Found multiple Projects for name: Arnold's Developers. Use ID instead or make sure Project names are unique [{false c89e9161-8350-44a5-81cf-9eb26605e195 2021-12-15T01:34:16.432Z 2021-12-15T01:34:16.432Z 725ffbc4-1eaa-46b3-9f0f-bdd66abf36fe Arnold's Developers auth0|61b2b34469c00900700e09b5 Admin {2021-12-10T01:54:12.279Z aws-users+api-key-prod-w9mnyfgh7vjgrkac@env0.com   Arnold's Key https://s.gravatar.com/avatar/375452b14b86af98b5c942b71f598626s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fak.png auth0|61b2b34469c00900700e09b5 2021-12-15T00:08:43.847Z map[isApiKey:true]} This T-800 is back for more exciting Infrastructure as Code work} {true c89e9161-8350-44a5-81cf-9eb26605e195 2021-12-15T01:30:02.571Z 2021-12-14T19:56:07.410Z 6fc6513b-7b90-48b7-922d-274973682eae Arnold's Developers auth0|61b2b34469c00900700e09b5 Admin {2021-12-10T01:54:12.279Z aws-users+api-key-prod-w9mnyfgh7vjgrkac@env0.com   Arnold's Key https://s.gravatar.com/avatar/375452b14b86af98b5c942b71f598626s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fak.png auth0|61b2b34469c00900700e09b5 2021-12-15T00:08:43.847Z map[isApiKey:true]} This T-800 is back for more exciting Infrastructure as Code work}]
 
   with module.template.module.template_project_assignment["frontend_layer"].data.env0_project.project["Arnold's Developers"],
   on .terraform/modules/template/modules/template_project_assignment/main.tf line 12, in data "env0_project" "project":
   12: data "env0_project" "project" {
```

repro steps:

1. use tf provider to create env0_project  name="dev"
2. use tf provider to delete env0_project  name="dev"
3. re-create env0_project name="dev"
4. use data provider env0_project to find project  name="dev"

**Comment by eranelbaz** [comment] 2021-12-21 16:34
Duplicate of https://github.com/env0/terraform-provider-env0/issues/80

**Closed by eranelbaz** 2021-12-21 16:34 UTC
Labels: bug
