### ISSUE TITLE
lexicographical sorting of configuration items

### ISSUE THREAD

**Issue by mmclane** [env0/terraform-provider-env0#459] opened 2022-08-01 13:31 UTC
I am trying to define my environment's configuration options using a map and a dynamic block.  I am doing this to make the terraform file much more readable and easier to maintain.  

Here is an example
```
locals {
  db-config = {
    allocated_storage = "40"
    db_instance_class = "db.t3.small"
    db_user           = "dbuser"
    service           = "myservice"
  }
}
resource "env0_environment" "automatron-db" {
  name       = "testdb"
  project_id = data.env0_project.this.id

  template_id                = data.env0_template.rds.id
  approve_plan_automatically = false
  deploy_on_push             = true
  run_plan_on_pull_requests  = true
  vcs_commands_alias         = "test-db"

  dynamic "configuration" {
    for_each = local.db-config
    content {
      name        = configuration.key
      value       = configuration.value
      type        = "terraform"
      schema_type = "string"
    }
  }
}

```

This code will apply and works great.  I can then create separate dynamic configuration blocks if I need to have a different type.  I find it much easier to read and adjust the settings compared to having each configuration setting block defined separately.

The problem is that future plans regularly want to update all of the configuration blocks that the dynamic block had created.  What I have determined is that the provider gets the options in a different order then what the map is in.  Terraform maps are automatically sorted in lexicographical order.  Its worth noting that if I look at the configuration options using terraform state show they are also listed in lexicographical order.  But when I run terraform plan, they seem to be returned in a different order.

**Comment by mmclane** [comment] 2022-08-01 13:51
I think my template variables are not listed in order and env0 is returning them in the order that the template is listing them.  I might be able to test that belief out but either way it would be better if the provider forced things into the same order that terraform assumes.

**Comment by yaronya** [comment] 2022-08-02 17:10
Hey @mmclane 
Thanks for the feedback and suggestion.

Which terraform version do you run? can you confirm that the lexicographical order is kept in previous versions as well?

**Comment by mmclane** [comment] 2022-08-03 12:10
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/env0/env0 v1.1.1

I believe the lexicographical order has been the way of things since the beginning.

**Comment by TomerHeber** [comment] 2022-08-18 14:25
@mmclane 

You are correct that it would be helpful (and more consistent) to have the provider return the variables in the same order.
The concern at the moment is that making this type of change might be a breaking change for other users of the provider.

I'm leaning toward closing this issue as "won't fix".

Let me know your thoughts and if you have any suggestions.

Thanks!

**Comment by mmclane** [comment] 2022-08-22 12:07
By not fixing this you making it so that our code is forced to be much longer and more difficult to read.  For instance, currently to create an environment using our rds template I have to write it as follows:

```
resource "env0_environment" "automatron-db" {
  name       = "example-db"
  project_id = data.env0_project.this.id

  template_id                = data.env0_template.rds.id
  approve_plan_automatically = false
  deploy_on_push             = true
  run_plan_on_pull_requests  = true
  vcs_commands_alias         = "mydb"

  configuration {
    name        = "db_instance_class"
    schema_type = "string"
    type        = "terraform"
    value       = "db.t3.small"
  }
  configuration {
    name        = "allocated_storage"
    schema_type = "string"
    type        = "terraform"
    value       = "40"
  }
  configuration {
    name        = "db_user"
    schema_type = "string"
    type        = "terraform"
    value       = "example"
  }
  configuration {
    name        = "service"
    schema_type = "string"
    type        = "terraform"
    value       = "example"
  }
  configuration {
    name        = "engine_version"
    schema_type = "string"
    type        = "terraform"
    value       = "11.13"
  }
}

```
That is a lot of duplicated code and much harder read.  What I would like to do instead is use a dynamic block as stated in my example.  So by not making this change your effectively breaking core terraform functionality, which I think is at least bad form and should be CLEARLY documented.  

Would it be possible to put have an optional configuration option on the provider that would toggle this behavior?  That way for those that want it they can have it work as is (which can be the default for now) and for those who want it sorted correctly they can set that option and have it work correctly?

**Comment by TomerHeber** [comment] 2022-08-22 14:28
@mmclane - understood! I'll keep you updated.

**Comment by TomerHeber** [comment] 2022-08-22 21:21
Hi @mmclane - I'm trying to reproduce the issue. But am getting consistent results.
I took your example. I'm running "plan" a few times, but no changes are reported.

Is there an easy way to reproduce it?

**Comment by mmclane** [comment] 2022-08-23 12:28
> Hi @mmclane - I'm trying to reproduce the issue. But am getting consistent results. I took your example. I'm running "plan" a few times, but no changes are reported.
> 
> Is there an easy way to reproduce it?

I think you might have to run an apply.  The issue as far as I remember is how the provider returns the list of resources from the infrastructure.

**Comment by mmclane** [comment] 2022-08-23 12:40
```
 8:37AM: ~/repos/docnet/infra-configs/config/env0/environments/m3test [resolve-drift|✚1⚑3] tfw:[default]  k8s:[main] > tfp

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # env0_environment.nothing will be created
  + resource "env0_environment" "nothing" {
      + approve_plan_automatically       = true
      + auto_deploy_on_path_changes_only = true
      + deploy_on_push                   = true
      + deployment_id                    = (known after apply)
      + force_destroy                    = true
      + id                               = (known after apply)
      + name                             = "m3test-nothing-test"
      + project_id                       = "acec4df8-387a-455b-bf90-3360bfb13472"
      + revision                         = (known after apply)
      + run_plan_on_pull_requests        = true
      + template_id                      = "953c2453-a526-4043-a1a2-dc156d544371"
      + workspace                        = "m3test"

      + configuration {
          + name  = "a"
          + type  = "terraform"
          + value = "avalue"
        }
      + configuration {
          + name  = "b"
          + type  = "terraform"
          + value = "bvalue"
        }
      + configuration {
          + name  = "c"
          + type  = "terraform"
          + value = "cvalue"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run
"terraform apply" now.
 8:37AM: ~/repos/docnet/infra-configs/config/env0/environments/m3test [resolve-drift|✚1⚑3] tfw:[default]  k8s:[main] > tfa

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # env0_environment.nothing will be created
  + resource "env0_environment" "nothing" {
      + approve_plan_automatically       = true
      + auto_deploy_on_path_changes_only = true
      + deploy_on_push                   = true
      + deployment_id                    = (known after apply)
      + force_destroy                    = true
      + id                               = (known after apply)
      + name                             = "m3test-nothing-test"
      + project_id                       = "acec4df8-387a-455b-bf90-3360bfb13472"
      + revision                         = (known after apply)
      + run_plan_on_pull_requests        = true
      + template_id                      = "953c2453-a526-4043-a1a2-dc156d544371"
      + workspace                        = "m3test"

      + configuration {
          + name  = "a"
          + type  = "terraform"
          + value = "avalue"
        }
      + configuration {
          + name  = "b"
          + type  = "terraform"
          + value = "bvalue"
        }
      + configuration {
          + name  = "c"
          + type  = "terraform"
          + value = "cvalue"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

env0_environment.nothing: Creating...
env0_environment.nothing: Creation complete after 5s [id=bcd9ddd9-38be-4dec-8bbc-2b25242a460f]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
 8:37AM: ~/repos/docnet/infra-configs/config/env0/environments/m3test [resolve-drift|✚1⚑3] tfw:[default]  k8s:[main] > tfp
env0_environment.nothing: Refreshing state... [id=bcd9ddd9-38be-4dec-8bbc-2b25242a460f]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # env0_environment.nothing has changed
  ~ resource "env0_environment" "nothing" {
        id                               = "bcd9ddd9-38be-4dec-8bbc-2b25242a460f"
        name                             = "m3test-nothing-test"
        # (10 unchanged attributes hidden)

      ~ configuration {
            name         = "a"
          + schema_enum  = []
            # (4 unchanged attributes hidden)
        }
      ~ configuration {
            name         = "b"
          + schema_enum  = []
            # (4 unchanged attributes hidden)
        }
      ~ configuration {
            name         = "c"
          + schema_enum  = []
            # (4 unchanged attributes hidden)
        }
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following
plan may include actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # env0_environment.nothing will be updated in-place
  ~ resource "env0_environment" "nothing" {
        id                               = "bcd9ddd9-38be-4dec-8bbc-2b25242a460f"
        name                             = "m3test-nothing-test"
        # (10 unchanged attributes hidden)

      ~ configuration {
            name         = "a"
          - schema_type  = "string" -> null
            # (4 unchanged attributes hidden)
        }
      ~ configuration {
            name         = "b"
          - schema_type  = "string" -> null
            # (4 unchanged attributes hidden)
        }
      ~ configuration {
            name         = "c"
          - schema_type  = "string" -> null
            # (4 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run
"terraform apply" now.
 8:38AM: ~/repos/docnet/infra-configs/config/env0/environments/m3test [resolve-drift|✚1⚑3] tfw:[default]  k8s:[main] > 
```

If you would like to get on a video call I can show you what I am talking about.  The real problem here is that if I use a dynamic block for the configuration to apply and then immediately run a plan, it wants to change all of the configuration.  This is due to the order in which the provider returns those configuration items.

**Comment by TomerHeber** [comment] 2022-08-25 01:54
@mmclane - thank you for the details.
This actually sounds like a bug. I'll let you know once a new version is released so you may test again.

**Comment by aessiane** [comment] 2022-08-25 08:10
I also have this bug quite often on my side, I'm glad a fix is being issued!

**Comment by TomerHeber** [comment] 2022-08-25 14:22
@aessiane and @mmclane - there's a new release 1.2.1.
Please let me know if it resolves the issue or if there are still some gaps.

Thanks!

**Comment by mmclane** [comment] 2022-08-25 14:34
So far in my limited testing that seems to take care of the issue.  I am going to update our terraform configs over today and tomorrow and let you know if I see any issues.

**Comment by TomerHeber** [comment] 2022-08-25 14:39
@mmclane - thanks for the update.
I'll wait for final confirmation before closing this issue.

**Comment by mmclane** [comment] 2022-08-25 14:55
This does not solve the issue.  

I have the following terraform config file that I used to create an environment
```
resource "env0_environment" "automatron-db" {
  name       = "automatron-db"
  project_id = data.env0_project.this.id

  template_id                = data.env0_template.rds.id
  approve_plan_automatically = false
  deploy_on_push             = true
  run_plan_on_pull_requests  = true
  vcs_commands_alias         = "automatron-db"

  configuration {
    name        = "db_instance_class"
    schema_type = "string"
    type        = "terraform"
    value       = "db.t3.small"
  }
  configuration {
    name        = "allocated_storage"
    schema_type = "string"
    type        = "terraform"
    value       = "40"
  }
  configuration {
    name        = "db_user"
    schema_type = "string"
    type        = "terraform"
    value       = "rundeckdb"
  }
  configuration {
    name        = "service"
    schema_type = "string"
    type        = "terraform"
    value       = "automatron"
  }
  configuration {
    name        = "engine_version"
    schema_type = "string"
    type        = "terraform"
    value       = "11.13"
  }
}

```
If I run a plan I get **No changes**

If I change this file to be the following
```
locals {
  automatron-db-config = {
    allocated_storage = "40"
    db_instance_class = "db.t3.small"
    db_user           = "rundeckdb"
    engine_version    = "11.13"
    service           = "automatron"
  }
}

resource "env0_environment" "automatron-db" {
  name       = "automatron-db"
  project_id = data.env0_project.this.id

  template_id                = data.env0_template.rds.id
  approve_plan_automatically = false
  deploy_on_push             = true
  run_plan_on_pull_requests  = true
  vcs_commands_alias         = "automatron-db"

  dynamic "configuration" {
    for_each = local.automatron-db-config
    content {
      name        = configuration.key
      value       = configuration.value
      type        = "terraform"
      schema_type = "string"
    }
  }
}

```
When I run plan I get the following
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.dev.env0_environment.automatron-db will be updated in-place
  ~ resource "env0_environment" "automatron-db" {
        id                               = "13ce5704-4ed7-4ddf-a721-a376647600d0"
        name                             = "automatron-db"
        # (10 unchanged attributes hidden)

      ~ configuration {
          ~ name         = "db_instance_class" -> "allocated_storage"
          ~ value        = "db.t3.small" -> "40"
            # (6 unchanged attributes hidden)
        }
      ~ configuration {
          ~ name         = "allocated_storage" -> "db_instance_class"
          ~ value        = "40" -> "db.t3.small"
            # (6 unchanged attributes hidden)
        }
      ~ configuration {
          ~ name         = "service" -> "engine_version"
          ~ value        = "automatron" -> "11.13"
            # (6 unchanged attributes hidden)
        }
      ~ configuration {
          ~ name         = "engine_version" -> "service"
          ~ value        = "11.13" -> "automatron"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run
"terraform apply" now.
Releasing state lock. This may take a few moments...
```

Changing the order of the map in locals.automatron-db-config doesn't change the behavior because terraform uses lexicographical sorting.

**Comment by TomerHeber** [comment] 2022-08-25 15:00
@mmclane - thanks! this is a different use case.
I think I understand what's happening:

This was in the following order:
```
  configuration {
    name        = "db_instance_class"
    schema_type = "string"
    type        = "terraform"
    value       = "db.t3.small"
  }
  configuration {
    name        = "allocated_storage"
    schema_type = "string"
    type        = "terraform"
    value       = "40"
  }
  configuration {
    name        = "db_user"
    schema_type = "string"
    type        = "terraform"
    value       = "rundeckdb"
  }
  configuration {
    name        = "service"
    schema_type = "string"
    type        = "terraform"
    value       = "automatron"
  }
  configuration {
    name        = "engine_version"
    schema_type = "string"
    type        = "terraform"
    value       = "11.13"
  }
```

switching to dynamic it become lexographical order - therefore there's a change.
Afterwards do you still have issues? I believe it should be fine afterwards.

**Comment by mmclane** [comment] 2022-08-25 15:04
What do you mean by afterwards?  After what?

**Comment by TomerHeber** [comment] 2022-08-25 15:13
@mmclane - sorry for being unclear. After applying the plan with dynamic ordering. My assumption is that next time you run a plan, it will show no diff.

**Comment by TomerHeber** [comment] 2022-08-25 17:23
@mmclane - got it. I'll have a look. Thanks for sending the example. I will keep you updated.

**Comment by TomerHeber** [comment] 2022-08-25 21:05
@mmclane - for some reason, I can't reproduce it. (using terraform 1.2.6)

First step - create an environment with explicit configurations:

```
configuration {
    name        = "db_instance_class"
    schema_type = "string"
    type        = "terraform"
    value       = "db.t3.small"
  }
  configuration {
    name        = "allocated_storage"
    schema_type = "string"
    type        = "terraform"
    value       = "40"
  }
  configuration {
    name        = "db_user"
    schema_type = "string"
    type        = "terraform"
    value       = "rundeckdb"
  }
  configuration {
    name        = "service"
    schema_type = "string"
    type        = "terraform"
    value       = "automatron"
  }
  configuration {
    name        = "engine_version"
    schema_type = "string"
    type        = "terraform"
    value       = "11.13"
  }
```

step 2: modify "dynamic" configuration:
```
  dynamic "configuration" {
    for_each = local.automatron-db-config
    content {
      name        = configuration.key
      value       = configuration.value
      type        = "terraform"
      schema_type = "string"
    }
  }
```
This step does show a diff - which is expected.
(I apply the change).

Step 3:
terraform plan - shows no diff (after the apply in step 2).

What am I missing?

**Comment by mmclane** [comment] 2022-08-26 14:41
That is not what I am experiencing with the same terraform version.  I have tried more than once.  I don't know if this makes a difference, but I did originally import this environment.

**Comment by avnerenv0** [comment] 2022-08-29 16:06
Hi @mmclane ,really sorry but we're not successful in recreating your issue.

If you can't provide us an example which reproduces the issue consistently - we can't really work on the issue, and will have to close it.

Thanks

**Comment by mmclane** [comment] 2022-08-29 18:13
@avnerenv0 I would be more then happy to meet with any of you to work on that.  It also seems that [aessiane](https://github.com/aessiane) seems to be having the issue so its not just me.

**Comment by mmclane** [comment] 2022-08-29 18:29
I would recommend trying the following to recreate the issue

1. Create an environment.  Create variables for this environment but do not have them in alphabetical order.
2. Create the terraform to match. Set the variables in alphabetical order, preferably using a dynamic block.
3. Import the environment.  
4. Run terraform plan.

**Comment by TomerHeber** [comment] 2022-08-29 19:54
Thanks, @mmclane - I do see some issues related to import.
I will investigate.

**Comment by mmclane** [comment] 2022-10-03 12:41
I am definitely still running into this being an issue.  Just today I am looking into why env0 is showing drift on the environment we use to create our other env0 environments.  I think its just that it wants to recreate all of the configuration items and change the order.

**Comment by mmclane** [comment] 2022-10-18 12:50
I can show you what I am seeing.  What is your email address?

**Comment by TomerHeber** [comment] 2022-10-21 20:26
Hi @mmclane - thank you for going over the issues with me.
I have created a PR. If you want to test it before release, you may do so via the branch. (Instructions in the README.md file).

I'll let you know once it's officially released.

**Closed** 2022-10-25 14:57 UTC
Labels: bug, question

**Comment by TomerHeber** [comment] 2022-10-25 16:05
@mmclane - I releasing 1.2.8. Please let me know if it resolves the issue for you.
Thanks!
