### ISSUE TITLE
Add create/update payload interfaces for project & configuration variable

### ISSUE THREAD

**Issue by yaronya** [env0/terraform-provider-env0#74] opened 2021-06-01 08:57 UTC
Currently `ConfigurationVariableCreate` and `ProjectCreate` receives flat parameters while all other resources get a payload interfaces. We should align them to have such interfaces.

**Comment by TomerHeber** [comment] 2022-03-08 16:14
After reviewing the code and discussing it with @yaronya - the issue is already resolved.
Closing this ticket.

**Closed by TomerHeber** 2022-03-08 16:14 UTC
Labels: good first issue
