### ISSUE TITLE
Error: Error loading state:      Error creating workspace ######: 403 Forbidden

### ISSUE THREAD

**Issue by shadyTS** [env0/terraform-provider-env0#528] opened 2022-11-05 19:05 UTC
we use env0 provider in Terraform code in order to create an environment in env0:

following provider configuration:
```
terraform {
  required_providers {
    env0 = {
      source  = "env0/env0"
      version = "1.2.7"
    }
  }
}

following our code that create the environment in env0:
resource "env0_environment" "######" {
  name                      = "######"
  project_id                = #####
  run_plan_on_pull_requests = true
  deploy_on_push            = true
  workspace                 = "#####"
  force_destroy             = true
  is_remote_backend         = true
  without_template_settings {
    repository           = "####"
    path                 = "######"
    bitbucket_client_key = var.bitbucket_client_key
    revision             = "####"
    type                 = "terraform"
    terraform_version    = "1.2.9"
  }
...
}
```

The environment has been created but the deployment failed with error:
```
 Error: Error loading state:
     Error creating workspace ####: 403 Forbidden
 ```
 
 Terraform failed to load the default state from the "remote" backend.
 State migration cannot occur unless the state can be loaded. Backend
 modification and state migration has been aborted. The state in both the
 source and the destination remain unmodified. Please resolve the
 above error and try again.

we check in setting of the environment in env0 ui and noticed that the  remote backend not enabled and we can enable it in the ui:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/116543252/200136749-8de68a6a-0524-4e1c-8ece-8dc780f20a44.png">

**Comment by TomerHeber** [comment] 2022-11-07 02:07
@yaronya - I reviewed the provider code. This might not be an issue with the provider.

**Comment by yaronya** [comment] 2022-11-07 08:14
@shadyTS correct me if I'm wrong please, but this was due to wrong bitbucket client key being used. Is that correct?
If so, can you please close the issue?

**Comment by shadyTS** [comment] 2022-11-07 08:24
Hi,
no, it's not the same issue

**Comment by yaronya** [comment] 2022-11-30 07:25
> @yaronya - I reviewed the provider code. This might not be an issue with the provider.

@TomerHeber were we able to reproduce it then? can you please shed some more light on this issue? 🙏

**Comment by TomerHeber** [comment] 2022-11-30 11:56
> 

@yaronya - I will check.

**Comment by TomerHeber** [comment] 2022-12-09 22:52
@yaronya I added "is_remote_backend" to both an existing environment and a new environment, in both cases it worked as expected.

![image](https://user-images.githubusercontent.com/12767692/206808162-074c4413-6035-4a0c-ba42-5bc0f55b66f3.png)

**Comment by TomerHeber** [comment] 2022-12-09 22:53
@yaronya - not it's grayed out (meaning I can't uncheck it in the UI). I don't know if it's expected or not.

**Comment by yaronya** [comment] 2022-12-28 08:56
Couldn't reproduce, closing.

**Closed by yaronya** 2022-12-28 08:56 UTC
Labels: bug, blocked

**Comment by yaronya** [comment] 2022-12-28 08:57
Re-closing as "not completed" (github 🙄 )

**Comment by yaronya** [comment] 2022-12-28 08:58
Re-closing as "not planned" (github 🙄 )
